apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fz4qyrbfl-go 
  janus-idp.io/tekton: fz4qyrbfl-go
  backstage.io/kubernetes-id: fz4qyrbfl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fz4qyrbfl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  